version: "3.7"

#https://stackoverflow.com/questions/46166304/docker-compose-volumes-without-colon

services:
  back:
    build:
      context: ./back
      target: dev
    container_name: nestjs
    env_file:
      - ./back/.env
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
      - 5555:5555
    networks:
      - transcendance

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./back/.env
    networks:
      - transcendance
    volumes:
      - pgdata:/var/lib/postgresql/data

  front:
    build:
      context: ./front
      target: dev
    container_name: react
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - back
    command: npm run dev
    ports:
      - 8080:8080
    networks:
      - transcendance

networks:
  transcendance:

volumes:
  pgdata:
